version: '3.8'
services:  
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laraapp_db
      MYSQL_ROOT_PASSWORD: acc
      MYSQL_USER: acc
      MYSQL_PASSWORD: acc
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9090:80

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 90:80
    volumes:
      - ./:/var/www/html
